version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
import: []
language: en,vi
includeRegExpList:
  - /[\p{Script_Extensions=Latin}\p{ASCII}]+/gu
words:
  - abbrs
  - ack
  - ani
  - apng
  - appcache
  - autofit
  - automator
  - beziér
  - booleanish
  - bouncized
  - calaboca
  - camelcase
  - ccw
  - classname
  - classnames
  - codepen
  - commitlint
  - composables
  - contenteditable
  - cooldown
  - cqh
  - cqw
  - csstype
  - cw
  - danmaku
  - datamix
  - datamixing
  - datamosh
  - datamoshes
  - datamoshing
  - demibold
  - dnd
  - dvh
  - dvw
  - easings
  - élastique
  - ele
  - endregion
  - esbuild
  - extralight
  - filedir
  - flyouts
  - fx
  - geq
  - glsl
  - gongche
  - highp
  - hmr
  - hotspot
  - hoverable
  - hsb
  - hsl
  - hsv
  - hta
  - hwb
  - idb
  - immer
  - jsdoc
  - jsdocs
  - kanban
  - kbd
  - kebabcase
  - keyframes
  - klass
  - languagedetector
  - lch
  - lengthenable
  - lengthenings
  - letterboxed
  - letterboxing
  - lightningcss
  - linebreak
  - lotties
  - ltr
  - luma
  - lumin
  - mht
  - mhtml
  - miscz
  - mograph
  - mographs
  - moz
  - multilayering
  - multisource
  - multitrack
  - nameof
  - neta
  - netaed
  - neutual
  - numberish
  - numpad
  - nums
  - nuxt
  - oem
  - ofx
  - oklab
  - oklch
  - ol
  - opsz
  - opszs
  - otf
  - otomad
  - otomads
  - overrider
  - oversaturation
  - pangu
  - parameterless
  - partialize
  - pillarbox
  - pillarboxed
  - pillarboxing
  - pingpong
  - pixi
  - portato
  - prelisten
  - prelistening
  - prelistenings
  - premade
  - prerenders
  - proxied
  - prve
  - prves
  - puyo
  - pv
  - quarternary
  - resw
  - resx
  - rgb
  - rtl
  - screencast
  - screencasts
  - segoe
  - shupelunker
  - singthesis
  - solfeggios
  - spherize
  - splitted
  - spn
  - styl
  - stylelint
  - subclips
  - subgrid
  - subgrids
  - subheaders
  - svgr
  - timecode
  - timecodes
  - touchpad
  - tsc
  - ttc
  - tts
  - ultrabold
  - unflipped
  - unhover
  - unlengthen
  - unlengthening
  - unlengthens
  - unmap
  - unpitched
  - unplugin
  - unremapping
  - unshifted
  - unsmooth
  - upsize
  - ust
  - utau
  - valtio
  - vite
  - vnd
  - vocaloid
  - vsq
  - vtt
  - wai
  - webgl
  - webp
  - winform
  - wj
  - wpf
  - xmlbuilder
  - xmp
  - xywh
  - xyz
  - yoooo
  - ytp
  - ytpmv
  - zustand
ignoreWords:
  - ranne
  - chaosinism
  - grantwoolard
  - cyahega
  - motosai
  - qo
  - zh
  - fcp
  - fc
  - tgs
  - ᵗ
  - ᵗsin
  - pn
  - shu
  - shuzo
  - matsuoka
  - rantetsu
  - inori
  - nocontent
  - tf
  - edg
  - menuitemcheckbox
  - menuitemradio
flagWords:
  - colour -> color
  - canot -> cannot
  - cancelled -> canceled
  - tunning -> tuning
  - seting -> setting
  - od -> of
  - draging -> dragging
  - splited -> splitted
  - pesudo -> pseudo
  - exitting -> exiting
  - trailling -> trailing
  - condif -> config
  - comflict -> conflict
  - typoef -> typeof
  - grey -> gray
  - oe -> or
  - filed -> field
  - interupt -> interrupt
