version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
import: []
language: en,vi
includeRegExpList:
  - /[\p{Script_Extensions=Latin}\p{ASCII}]+/gu
words:
  - abbrs
  - ack
  - amoled
  - ani
  - apng
  - appcache
  - arccos
  - arccot
  - arcsin
  - arctan
  - autofit
  - automator
  - backdoors
  - backface
  - beziér
  - bg
  - bgm
  - booleanish
  - bouncized
  - breakbeat
  - calaboca
  - camelcase
  - ccw
  - cjk
  - classname
  - classnames
  - clr
  - codepen
  - commitlint
  - composables
  - contenteditable
  - cooldown
  - cqh
  - cqmax
  - cqmin
  - cqw
  - csstype
  - cw
  - danmaku
  - datamix
  - datamixing
  - datamosh
  - datamoshes
  - datamoshing
  - demibold
  - desynchronize
  - desynchronizes
  - dnd
  - dppx
  - drm
  - dvh
  - dvw
  - easings
  - élastique
  - ele
  - endregion
  - esbuild
  - evaluable
  - extralight
  - filedir
  - flyouts
  - fullwidth
  - fx
  - geq
  - glsl
  - gongche
  - gpt
  - grayscale
  - halfwidth
  - highp
  - hmr
  - hotspot
  - hoverable
  - hsb
  - hsl
  - hsv
  - hta
  - hwb
  - idb
  - img
  - immer
  - indet
  - jipt
  - jsdoc
  - jsdocs
  - kanban
  - kbd
  - kebabcase
  - keyframes
  - klass
  - laggy
  - languagedetector
  - lch
  - lengthenable
  - lengthenings
  - letterboxed
  - letterboxing
  - lightningcss
  - linebreak
  - lotties
  - ltr
  - luma
  - lumin
  - lvh
  - lvs
  - lvw
  - magix
  - mathml
  - mht
  - mhtml
  - miscz
  - misplacements
  - mograph
  - mographs
  - moz
  - mscorlib
  - multilayering
  - multisource
  - multitrack
  - nameof
  - neta
  - netaed
  - neutual
  - notdeprecated
  - numberish
  - numpad
  - nums
  - nuxt
  - oem
  - ofx
  - oklab
  - oklch
  - ol
  - opsz
  - opszs
  - otf
  - otomad
  - otomadhelper
  - otomads
  - overrider
  - oversaturation
  - pangu
  - parameterless
  - partialize
  - pillarbox
  - pillarboxed
  - pillarboxing
  - pingpong
  - pixi
  - portato
  - posterize
  - prelisten
  - prelistening
  - prelistenings
  - premade
  - prerenders
  - propertize
  - propertizer
  - proxied
  - prve
  - prves
  - puyo
  - pv
  - pxify
  - qrcode
  - quarternary
  - resw
  - resx
  - rgb
  - rtl
  - screencast
  - screencasts
  - segoe
  - semilight
  - shupelunker
  - singthesis
  - sln
  - solfège
  - solfèges
  - solfeggios
  - spherize
  - spn
  - styl
  - stylelint
  - subclips
  - subgrid
  - subgrids
  - subheaders
  - svgr
  - svgs
  - svh
  - svw
  - timecode
  - timecodes
  - timeflow
  - toggleable
  - touchpad
  - tp
  - tsc
  - tt
  - ttc
  - tts
  - ultrabold
  - unflipped
  - unfocusable
  - unhover
  - unlengthen
  - unlengthening
  - unlengthens
  - unmap
  - unpitched
  - unplugin
  - unremapping
  - unshifted
  - unsmooth
  - unvocalized
  - upsize
  - ust
  - utau
  - utf
  - valtio
  - vec
  - vite
  - vnd
  - vocaloid
  - voicebank
  - vsq
  - vtt
  - wai
  - webgl
  - webp
  - winform
  - wj
  - Woolard
  - wpf
  - xmlbuilder
  - xmp
  - xy
  - xywh
  - xyz
  - yi
  - yoooo
  - yozora
  - ytp
  - ytpmv
  - zplane
  - zustand
ignoreWords:
  - ranne
  - chaosinism
  - grantwoolard
  - cyahega
  - motosai
  - qo
  - zh
  - fcp
  - fc
  - tgs
  - ᵗ
  - ᵗsin
  - pn
  - shu
  - shuzo
  - matsuoka
  - rantetsu
  - inori
  - nocontent
  - tf
  - edg
  - menuitemcheckbox
  - menuitemradio
  - ized
  - gongshang
  - lyulyu
  - lülü
  - gōngchě
  - gōngshāng
  - lǜlǚ
  - crwdns
  - crwdne
  - crwdnd
  - oxc
flagWords:
  - colour -> color
  - canot -> cannot
  - cancelled -> canceled
  - tunning -> tuning
  - seting -> setting
  - od -> of
  - draging -> dragging
  - splited -> split
  - splitted -> split
  - pesudo -> pseudo
  - exitting -> exiting
  - trailling -> trailing
  - condif -> config
  - comflict -> conflict
  - typoef -> typeof
  - grey -> gray
  - oe -> or
  - filed -> field
  - interupt -> interrupt
  - prefered -> preferred
  - preffered -> preferred
  - evaluatable -> evaluable
  - accidently -> accidentally
  - infomation -> information
  - paning -> panning
  - coed -> code
  - spped -> speed
  - positon -> position
  - expoer -> export
  - interger -> integer
  - intergers -> integers
  - togglable -> toggleable
  - bluring -> blurring
  - stirng -> string
  - writeable -> writable
  - disablable -> canBeDisabled
  - disableable -> canBeDisabled
  - disabledable -> canBeDisabled
  - Disablable -> CanBeDisabled
  - Disableable -> CanBeDisabled
  - Disabledable -> CanBeDisabled
  - formated -> formatted
